version: "3.9"

services:
  rtsp-to-web:
    build: ./rtsptoweb/
    container_name: rtsp-to-web
    restart: always
    networks:
      - rtsp-network
    ports:
      - "80:80"
    expose:
      - "554"
    volumes:
      - /home/ubuntu/app/config.json:/config/config.json
    environment:
      TZ: ${TZ}
    env_file:
      - .env

  rtsp-recorder:
    build: ./recorder/
    restart: always
    networks:
      - rtsp-network
    volumes:
      - /var/log:/var/log
    environment:
      TZ: ${TZ}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    deploy:
      replicas: 2 #${NUM_CAMERAS:-1}
    command: >
      sh -c "export cam_number=$(echo $HOSTNAME | awk -F'-' '{print $NF}') &&
             python3 rtsp_record.py"

networks:
  rtsp-network:
    driver: bridge
