name: Trigger-Deploy
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  
jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      ### 🔍 **Lint Dockerfiles with hadolint**
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "**/Dockerfile"

      ### 🐍 **Lint Python files with Super-Linter**
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON: true
          VALIDATE_DOCKERFILE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      ### 🛠 **Run pre-commit hooks**
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

  trigger:
    name: Trigger Ansible Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PAT_TOKEN_GITHUB }}" \
               https://api.github.com/repos/KastonI/final-project-cfg/dispatches \
               -d '{"event_type": "push-to-src-repo"}'
