name: Trigger-Deploy
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger:
    name: Trigger Ansible Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PAT_TOKEN_GITHUB }}" \
               https://api.github.com/repos/KastonI/final-project-cfg/dispatches \
               -d '{"event_type": "external-trigger"}'
