name: Trigger-Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
  
jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      ### 🐍 Lint Python files with Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger:
    name: Trigger Ansible Deploy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Send repository_dispatch event
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PAT_TOKEN_GITHUB }}" \
               https://api.github.com/repos/KastonI/final-project-cfg/dispatches \
               -d '{"event_type": "push-to-src-repo"}'
